### ISSUE TITLE
Populate footer with working links

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphadvocates/webapp#1]
### DAO
* Overview
* Members
* Community Grant
* FAQ

### Advocates
* Overview
* How to Join
* Active Members
* Roles
* Endorsement Catalog

### Follow Us
* Discord
* Telegram
* Twitter
* Endorsement Catalog

### Legal (Do we need this as stand alone section?)
* Privacy Policy
* Terms of Service
* DAO Charter?
* Payments (Do we need this link?)

**Comment by ashutosh887** [comment]
I can replace the links
Please assign the issue to me if not resolved yet @alex-pakalniskis

**Comment by dylviz** [comment]
Footer pruned in latest push. New requests can add links as needed
#17
