### ISSUE TITLE
Investigate Cuda Pages as alternative for member profiles

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphadvocates/webapp#5]
## Social media reference landing page for web3 people (think Linktree):
* Home page: https://barracuda.io/
* DAO Directory: https://barracuda.io/discover

### Examples
* Bankless DAO: https://barracuda.io/BanklessDAO
* Gnosis Chain: https://barracuda.io/gnosischain
* Nodeify (Vince): https://barracuda.io/nodeify

### Questions pertaining to use of Clickup as sole source of truth:
* Can Graph Advocates update their information as they join and leave roles?
  * If no, how is information updated currently?

### Concerns pertaining to use of Cuda Pages to complement Clickup:
* Advocates could post links/content on their profile that does not align with our collective mission or community guidelines. Could provide clear guidelines that make it known your profile will be removed from the site if it is in breach of accepted community conduct

**Comment by ashutosh887** [comment]
@alex-pakalniskis 
I would like to work on this

**Comment by dylviz** [comment]
Cuda pages no longer exists. They went out of business or something. Closing for now
